---
- name: Add user jpriddy with password
  hosts: all
  become: yes

  tasks:   #using custom creds stored in controler 
    - name: Create user jpriddy, set password and add to users and wheel groups
      ansible.builtin.user:
        name: "{{ user_account_username }}"
        append: yes
        generate_ssh_key: yes
        password: "{{ user_account_password }}"
        groups:
          - users
          - wheel