- name: Add user jpriddy with password
  hosts: all
  become: yes

  tasks:
    - name: Create user jpriddy and add to users and wheel groups
      user:
        name: "{{ user_account_username }}"
        append: yes  # Append to existing /etc/passwd file
        generate_ssh_key: yes
        password: "{{ lookup('env', 'YOUR_PASSWORD_VARIABLE') }}"
        groups:  # Add user to groups (optional)
          - users
          - wheel