- name: Add user jpriddy with password
  hosts: all
  become: yes

  tasks:
    - name: Create user jpriddy and add to users and wheel groups
      user:
        name: "{{ user_account_username }}"
        append: yes  # Append to existing /etc/passwd file
        groups:  # Add user to groups (optional)
          - users
          - wheel

    - name: Set password for jpriddy
      user:
        name: "{{ user_account_username }}"
        password: "{{ '1{{ user_account_password }}' | password_hash('sha512') }}"
        append: yes