---
- name: Install/Configure autofs
  hosts: all
  become: true
  tasks:

   - name: Install autofs
     ansible.builtin.dnf:
      name: autofs
      state: present

   - name: Start and enable autofs
     ansible.builtin.systemd:
      name: autofs
      state: reloaded
      enabled: true

   # - name: Create automounter configuration file
   #  template:
   #     src: templates/automounter.conf.j2
   #     dest: /etc/auto.master.d/auto.ansible
   #     owner: root
   #     group: root
   #     mode: '0644'  
