- name: Add user jpriddy with password
  hosts: all
  become: yes

  tasks:
    - name: Create user jpriddy and add to users and wheel groups
      user:
        name: jpriddy
        append: yes  # Append to existing /etc/passwd file
        groups:  # Add user to groups (optional)
          - users
          - wheel

    - name: Set password for jpriddy
      user:
        name: jpriddy
        password: "{ jpriddy_password }"
        append: yes