---
- name: OS Configuration
  hosts: all

  tasks:

    - name: Install a bunch of packages from the base repos
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - bash-completion
        - rsync

    - name: Configure timesync with system role
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.timesync
      vars:
        timesync_ntp_servers:
          - hostname: 192.168.1.1
            iburst: true

    - name: Customize ssh server with system role redhat.rhel_system_roles.sshd
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.sshd
      vars:
        sshd_X11Forwarding: yes
        sshd_GSSAPIAuthentication: yes
        sshd_ChallengeResponseAuthentication: yes
        sshd_AllowTcpForwarding: yes

    - name: Create/replace sssd.conf
      ansible.builtin.template:
        src: templates/sssd.conf.j2
        mode: '0600'
        dest: /etc/sssd/sssd.conf

    - name: Install guest agent if virtualized
      ansible.builtin.dnf:
        name: qemu-guest-agent
        state: present
      when: ansible_virtualization_role == "guest"
