---
- name: Clean up, update, and prepare Fedora system
  hosts: all
  become: true

  tasks:
    - name: Install remove-retired-packages
      ansible.builtin.dnf:
        name: remove-retired-packages
        state: present

    - name: Run remove-retired-packages
      ansible.builtin.command: remove-retired-packages
      register: retired_packages_result
      changed_when: "'No retired packages found' not in retired_packages_result.stdout"

    - name: Remove duplicate packages
      ansible.builtin.command: dnf remove --duplicates -y
      register: remove_duplicates_result
      changed_when: remove_duplicates_result.rc == 0

    - name: Run dnf autoremove
      ansible.builtin.dnf:
        autoremove: true

    - name: Install clean-rpm-gpg-pubkey
      ansible.builtin.dnf:
        name: clean-rpm-gpg-pubkey
        state: present

    - name: Run clean-rpm-gpg-pubkey
      ansible.builtin.command: clean-rpm-gpg-pubkey
      register: clean_gpg_result
      changed_when: "'Nothing to do' not in clean_gpg_result.stdout"

    - name: Run dnf distro-sync
      ansible.builtin.command: dnf distro-sync -y
      register: distro_sync_result
      changed_when: distro_sync_result.rc == 0

    - name: Run fixfiles -B onboot
      ansible.builtin.command: fixfiles -B onboot
      register: fixfiles_result
      changed_when: fixfiles_result.rc == 0

    - name: Display results
      ansible.builtin.debug:
        msg:
          - "Retired packages: {{ retired_packages_result.stdout }}"
          - "Remove duplicates: {{ remove_duplicates_result.stdout }}"
          - "Clean GPG keys: {{ clean_gpg_result.stdout }}"
          - "Distro sync: {{ distro_sync_result.stdout }}"
          - "Fixfiles: {{ fixfiles_result.stdout }}"

    - name: clean up any leftover dnf cache
      ansible.builtin.command: rm -rf /var/cache/dnf
      register: cleancache_result
      changed_when: cleancache_result.rc == 0
