---
- name: Join IPA domain
  hosts: all

  tasks:
    - name: Install required python packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - python3-ipalib

    - name: Uninstall IPA client (not the packages)
      ansible.builtin.include_role:
        name: redhat.rhel_idm.ipaclient
      vars:
        ipa_client_state: absent

    - name: Deploy and configure IPA client
      ansible.builtin.include_role:
        name: redhat.rhel_idm.ipaclient
      vars:
        ipa_client_state: present
        ipaadmin_password: "{ freeipa_admin_password }"
        ipaclient_mkhomedir: true
        ipaclient_ntp_servers: 192.168.1.1
        ipaclient_ssh_trust_dns: true
        ipaclient_allow_repair: true
        ipaclient_force_join: true
        ipaclient_configure_firefox: true
        ipaclient_all_ip_addresses: true
        ipaclient_subid: true

    - name: Install realmd for completeness
      ansible.builtin.dnf:
        name: realmd
        state: present

    - name: Create conf file for krb5 to support short hostnames
      ansible.builtin.template:
        src: templates/50-krb5-short-hostnames.conf
        dest: /etc/krb5.conf.d/50-krb5-short-hostnames.conf
        mode: "0644"

    - name: Create conf file for sshd to support short hostnames
      ansible.builtin.template:
        src: templates/60-ssh-short-hostnames.conf.j2
        dest: /etc/ssh/sshd_config.d/60-ssh-short-hostnames.conf
        mode: "0644"
