---
- name: Set hostname of server
  hosts: all

  tasks:
    - name: Set system hostname to ansible inventory hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}.jpriddy.lan"
        use: systemd

    - name: Configure /etc/hostname since the hostname module can't/won't
      ansible.builtin.copy:
        content: "{{ inventory_hostname }}.jpriddy.lan"
        dest: /etc/hostname
        owner: root
        group: root
        mode: "0644"
