---
- name: Set hostname of server
  hosts: all
  become: true
  tasks:

    - name: Set active hostname
      ansible.builtin.hostname:
        name: '{{ inventory_hostname }}.jpriddy.lan'
        use: systemd

    - name: Configure /etc/hostname for permanence since the hostname module can't
      ansible.builtin.copy:
        content: '{{ inventory_hostname }}.jpriddy.lan'
        dest: /etc/hostname
        owner: root
        group: root
        mode: '0644'
