---
- name: Configure monitoring and metrics gathering
  hosts: all
  
  tasks:

    - name: Install glances
      ansible.builtin.dnf:
        name: glances
        state: present

    - name: Replacing systemd service file
      ansible.builtin.template:
        src: templates/glances.service.j2
        mode: '0644'
        dest: /usr/lib/systemd/system/glances.service

    - name: Reload glances
      ansible.builtin.systemd:
        name: glances
        daemon_reload: true
        state: reloaded
