---
- name: Install and start custom iperf3 systemd service for bandwith testing
  hosts: all

  tasks:

    - name: Install iperf3
      ansible.builtin.dnf:
        name: iperf3
        state: present

    - name: Create systemd service file
      ansible.builtin.template:
        src: templates/iperf3.service.j2
        mode: '0644'
        dest: /usr/lib/systemd/system/iperf3.service       

    - name: Pick up new iperf3 service with systemd and then enable/start
      ansible.builtin.systemd:
        name: iperf3
        state: reloaded
        daemon_reload: true
        enabled: true
