---
- name: Setup /etc/fstab for NFS shares from synology
  hosts: all

  vars:
    nfs_mounts:
      - { name: download, server_path: /volume1/download }
      # all others on volume2
      - { name: iso, server_path: /volume2/iso }
      # done via kdump - { name: crash, server_path: /volume2/crash }
      - { name: scratch, server_path: /volume2/scratch }
      - { name: backup, server_path: /volume2/backup }
      - { name: web, server_path: /volume2/web }
      - { name: music, server_path: /volume2/music }
      - { name: document, server_path: /volume2/document }
      - { name: video, server_path: /volume2/video }

  tasks:

    - name: Ensure nfs-utils is installed
      ansible.builtin.dnf:
        name: nfs-utils
        state: present

    - name: Mount NFS shares
      ansible.posix.mount:
        src: "192.168.1.30:{{ item.server_path }}"
        path: "/synology/{{ item.name }}"
        fstype: nfs
        opts: "intr,rw,relatime,vers=3,rsize=131072,wsize=131072,namlen=255,hard,timeo=600,retrans=2,sec=sys,local_lock=none,_netdev"
        state: mounted
      with_items: "{{ nfs_mounts }}"
