---
- name: Install Netdata
  hosts: all

  tasks:

    - name: Install openssl
      ansible.builtin.dnf:
        name: openssl
        state: present

    - name: Download the installation script from internet
      ansible.builtin.get_url:
        url: https://my-netdata.io/kickstart.sh
        dest: /tmp/netdata_kickstart.sh
        mode: +x

    - name: Run the installer
      ansible.builtin.command: /tmp/netdata_kickstart.sh  --native-only --dont-wait --disable-telemetry --non-interactive
      register: output
      #changed_when: my_output.rc != 0

    - name: Replace config file
      ansible.builtin.template:
        src: templates/netdata.conf.j2
        dest: /etc/netdata/netdata.conf
        owner: root
        group: root
        mode: '0644'

    - name: Restart Netdata
      ansible.builtin.service:
        name: netdata
        state: restarted
