---
- name: Install Netdata
  hosts: all

  tasks:

    - name: Install openssl prereq
      ansible.builtin.dnf:
        name: openssl
        state: present

    - name: Add netdata repo gpg key
      ansible.builtin.rpm_key:
        key: "https://repo.netdata.cloud/netdatabot.gpg.key"
        state: present
      when: ansible_distribution == 'Fedora'

    - name: Download netdata repo config rpm
      ansible.builtin.get_url:
        url: https://repo.netdata.cloud/repos/repoconfig/fedora/41/x86_64/netdata-repo-edge-4-1.noarch.rpm
        dest: /tmp/netdata-repo-edge-4-1.noarch.rpm
        mode: '0644'

    - name: Install repo config rpm for edge (no fedora 41 package yet in stable)
      ansible.builtin.dnf:
        name: /tmp/netdata-repo-edge-4-1.noarch.rpm
        validate_certs: false
        state: present

    - name: Install netdata
      ansible.builtin.dnf:
        name: netdata
        state: present

    - name: Replace config file
      ansible.builtin.template:
        src: templates/netdata.conf.j2
        dest: /etc/netdata/netdata.conf
        owner: root
        group: root
        mode: '0644'

    - name: Restart Netdata
      ansible.builtin.service:
        name: netdata
        state: restarted



#failing saying the package doesnt exist -- repo config issue?
#    - name: Download the installation script from internet
#      ansible.builtin.get_url:
#        url: https://my-netdata.io/kickstart.sh
#        dest: /tmp/netdata_kickstart.sh
#        mode: +x
#
#    - name: Run the installer
#      ansible.builtin.command: /tmp/netdata_kickstart.sh  --no-updates --native-only --dont-wait --disable-telemetry --non-interactive --nightly-channel
#      register: output
#      #changed_when: my_output.rc != 0