---
- name: Install packagse for binding issues
  hosts: all

  tasks:

    - name: Install python related packages with a shell to resolve binding issues
      ansible.builtin.shell: "dnf install -y python3-libdnf5 python3-dnf python3-libselinux python3-dnf-plugin-rpmconf python3-deltarpm python3-pyrpm"