---
- name: Configure additional repos for Fedora
  hosts: all
  become: true
  tasks:

    - name: Import gpg keys for rpmfusion
      ansible.builtin.rpm_key:
        key: "{{ item }}"
        state: present
      loop:
        - "https://download1.rpmfusion.org/free/fedora/RPM-GPG-KEY-rpmfusion-free-fedora-2020"
        - "https://download1.rpmfusion.org/nonfree/fedora/RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"
      when: ansible_distribution == 'Fedora'
      
    - name: Install repo file for rpmfusion
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
        - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
      when: ansible_distribution == 'Fedora'