---
- name: Configure additional repos for Fedora
  hosts: all
  
  tasks:

    - name: Import gpg keys for free rpmfusion
      ansible.builtin.rpm_key:
        key: https://download1.rpmfusion.org/free/fedora/RPM-GPG-KEY-rpmfusion-free-fedora-2020
        state: present
      when: ansible_distribution == 'Fedora'

    - name: Import gpg keys for free rpmfusion
      ansible.builtin.rpm_key:
        key: https://download1.rpmfusion.org/nonfree/fedora/RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
        state: present
      when: ansible_distribution == 'Fedora'    


    - name: Install repo file for rpmfusion free
      ansible.builtin.dnf:
        name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm
        state: present
      when: ansible_distribution == 'Fedora'

    - name: Install repo file for rpmfusion nonfree
      ansible.builtin.dnf:
        name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm
        state: present
      when: ansible_distribution == 'Fedora'