---
- name: Configure additional repos for Fedora
  hosts: all

  tasks:

    - name: Add rpmfustion repo gpg keys
      ansible.builtin.rpm_key:
        key: "{{ item }}"
        state: present
      with_items:
        - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"
        - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"
      when: ansible_distribution == 'Fedora'

    - name: Install rpmfusion repo packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
        validate_certs: false
      with_items:
        - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
        - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"
      when: ansible_distribution == 'Fedora'