---
- name: Modify sudoers configuration
  hosts: all
  become: true
  tasks:
    
    - name: Remove default rule for wheel group
      sudoers:
        commands: '%wheel  ALL=(ALL)       ALL'
        name: wheel_with_passwd
        append: yes

    - name: Add rule to sudoers for no passwd with wheel group
      sudoers:
        commands: '%wheel ALL=(ALL) NOPASSWD: ALL'
        name: wheel_without_passwd
        append: yes
    

 