---
- name: Modify syslog for graylog
  hosts: all 
  tasks:

    - name: Ensure rsysliog is installed
      ansible.builtin.dnf:
        name: rsyslog
        state: present

    - name: Create rsyslog configuration file
      template:
        src: templates/99-graylog.conf.j2 
        dest: /etc/rsyslog.d/99-graylog.conf

    - name: Restart rsyslog service
      service:
        name: rsyslog
        state: restarted

  vars:
    graylog_server: db.jpriddy.lan 
    graylog_port: 514 