---
- name: Modify syslog for synology
  hosts: all 
  tasks:


    - name: Ensure rsysliog is installed
      ansible.builtin.dnf:
        name: rsyslog
        state: present

    - name: Create rsyslog configuration file
      template:
        src: templates/99-synology.conf.j2 
        dest: /etc/rsyslog.d/99-synology.conf

    - name: Restart rsyslog service
      service:
        name: rsyslog
        state: restarted

  vars:
    synology_server: synology.jpriddy.lan 
    synology_port: 514 