---
- name: Configure os tuning 
  hosts: all
  become: true
  tasks:

    - name: Install packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - tuned

    - name: Enable and start tuned
      ansible.builtin.systemd:
        name: tuned
        enabled: true
        state: restarted

    - name: Setup tuned for auto_profile
      ansible.builtin.command:
        cmd: "/usr/sbin/tuned-adm auto_profile"