---
- name: Configure os tuning
  hosts: all

  tasks:

    - name: Install packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - tuned

    - name: Setup tuned for auto_profile
      ansible.builtin.command:
        cmd: "/usr/sbin/tuned-adm auto_profile"
      register: output
      changed_when: output.rc != 0

    - name: Enable and start tuned
      ansible.builtin.systemd:
        name: tuned
        enabled: true
        state: started
