---
- name: Upgrade system
  hosts: all
  become: true

  tasks:
      - name: Download the packages
        ansible.builtin.command: dnf system-upgrade --releasever=latest doanload
        
      - name: Upgrade and reboot
        ansible.builtin.command: sudo dnf system-upgrade reboot

      - name: Wait for server to come back online
        wait_for_connection:
          delay: 60
          timeout: 600